<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>MBFD Executive Evaluation Report</title>
    <style>
        @page { margin: 1in; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 11pt; line-height: 1.6; color: #1a1a1a; }
        .header { text-align: center; margin-bottom: 40px; border-bottom: 3px solid #1e3a5f; padding-bottom: 20px; }
        .header img { max-width: 120px; margin-bottom: 10px; }
        .header h1 { font-size: 22pt; color: #1e3a5f; margin: 0 0 5px 0; }
        .header h2 { font-size: 14pt; color: #4a4a4a; margin: 0 0 5px 0; font-weight: normal; }
        .header .subtitle { font-size: 10pt; color: #888; }
        .section { margin-bottom: 30px; }
        .section h3 { font-size: 14pt; color: #1e3a5f; border-bottom: 1px solid #ddd; padding-bottom: 5px; margin-bottom: 15px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background-color: #1e3a5f; color: white; padding: 10px 12px; text-align: left; font-size: 10pt; }
        td { padding: 8px 12px; border-bottom: 1px solid #eee; font-size: 10pt; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .score-badge { display: inline-block; padding: 3px 10px; border-radius: 12px; font-weight: bold; font-size: 10pt; }
        .score-high { background-color: #d4edda; color: #155724; }
        .score-mid { background-color: #fff3cd; color: #856404; }
        .score-low { background-color: #f8d7da; color: #721c24; }
        .ai-report { white-space: pre-wrap; background: #f8f9fa; padding: 20px; border-radius: 8px; border-left: 4px solid #1e3a5f; }
        .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 9pt; color: #888; }
        .confidential { color: #c0392b; font-weight: bold; text-transform: uppercase; font-size: 9pt; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Miami Beach Fire Department</h1>
        <h2>Workgroup Evaluation Executive Report</h2>
        <div class="subtitle">Session: {{ $session->name }} | Generated: {{ $generatedAt }}</div>
        <div class="confidential">Confidential — For Health & Safety Committee Use Only</div>
    </div>

    <div class="section">
        <h3>Product Evaluation Summary</h3>
        <table>
            <thead>
                <tr>
                    <th>Rank</th>
                    <th>Product</th>
                    <th>Manufacturer</th>
                    <th>Category</th>
                    <th>Avg Score</th>
                    <th>Evaluations</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($products as $index => $product)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td><strong>{{ $product['name'] }}</strong></td>
                        <td>{{ $product['manufacturer'] }}</td>
                        <td>{{ $product['category'] }}</td>
                        <td>
                            @php
                                $score = is_numeric($product['avg_score']) ? (float)$product['avg_score'] : 0;
                                $class = $score >= 80 ? 'score-high' : ($score >= 60 ? 'score-mid' : 'score-low');
                            @endphp
                            <span class="score-badge {{ $class }}">{{ $product['avg_score'] }}</span>
                        </td>
                        <td>{{ $product['response_count'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="section">
        <h3>Analysis & Recommendation</h3>
        <div class="ai-report">{{ $aiReport }}</div>
    </div>

    <div class="footer">
        <p>This report was generated by the MBFD Eval Feedback Hub. Scores represent weighted averages from official evaluators using the Universal Evaluation Rubric.</p>
        <p>&copy; {{ date('Y') }} Miami Beach Fire Department | www.mbfdhub.com</p>
    </div>
</body>
</html>
