// Import real MBFD data - simplified version
// Clear and import equipment

\DB::table('stock_mutations')->truncate();
\DB::table('equipment_items')->truncate();
\DB::table('apparatuses')->truncate();
echo "Cleared existing data\n";

$stockableType = (new \App\Models\EquipmentItem)->getMorphClass();

$equipmentData = [
    ['Mounts', 2, 'Supply Closet', 'A1'],
    ['Aerial Master Stream Tips', 4, 'Supply Closet', 'A1'],
    ['Stream Straightener', 1, 'Supply Closet', 'A1'],
    ['Nozzle Teeth Packs', 17, 'Supply Closet', 'A1'],
    ['Stortz Caps', 6, 'Supply Closet', 'A2'],
    ['4" Cap', 1, 'Supply Closet', 'A2'],
    ['5" Caps', 4, 'Supply Closet', 'A2'],
    ['6" Caps', 8, 'Supply Closet', 'A2'],
    ['6" Gaskets', 4, 'Supply Closet', 'A2'],
    ['5" Gaskets', 16, 'Supply Closet', 'A2'],
    ['5" Suction Gaskets', 10, 'Supply Closet', 'A2'],
    ['2 1/2" Gaskets', 18, 'Supply Closet', 'A2'],
    ['1 1/2" Gaskets', 9, 'Supply Closet', 'A2'],
    ['Misc. Gaskets', 4, 'Supply Closet', 'A2'],
    ['6" to 4" Reducers', 4, 'Supply Closet', 'A3'],
    ['6" to 2" Reducer', 1, 'Supply Closet', 'A3'],
    ['4" to 2 1/2" Reducers', 2, 'Supply Closet', 'A3'],
    ['Stortz Connection with 4" Male', 6, 'Supply Closet', 'A3'],
    ['Stortz Connection with 5" Male', 4, 'Supply Closet', 'A3'],
    ['Stortz Connection with 6" Male', 1, 'Supply Closet', 'A3'],
    ['Stortz Connection with 6" Female', 2, 'Supply Closet', 'A3'],
    ['5" to 4" Reducers', 3, 'Supply Closet', 'A3'],
    ['4 1/2" Adapter', 1, 'Supply Closet', 'A3'],
    ['Stortz Connection with 4" Female', 1, 'Supply Closet', 'A3'],
    ['Hydrant Assist Valve', 1, 'Supply Closet', 'A4'],
    ['Intake', 1, 'Supply Closet', 'A4'],
    ['Stortz Elbow to 4" Female', 5, 'Supply Closet', 'A4'],
    ['Misc. Adapters', 2, 'Supply Closet', 'A4'],
    ['Foam Boot', 8, 'Supply Closet', 'B1'],
    ['75psi 175gpm Fog Tips', 10, 'Supply Closet', 'B2'],
    ['100psi 325gpm Fog Tips', 1, 'Supply Closet', 'B2'],
    ['75psi 200gpm Fog Tips', 1, 'Supply Closet', 'B2'],
    ['Selectomatic Nozzle Tip', 1, 'Supply Closet', 'B2'],
    ['Other Fog Tips', 5, 'Supply Closet', 'B2'],
    ['Glow in the Dark Stream Adjusters', 2, 'Supply Closet', 'B2'],
    ['Bag of Brass Set Screws', 1, 'Supply Closet', 'B2'],
    ['Red Box Misc.', 1, 'Supply Closet', 'B2'],
    ['Appliance Mounts', 9, 'Supply Closet', 'B2'],
    ['Handle Playpipes', 3, 'Supply Closet', 'B3'],
    ['Incline Gates', 3, 'Supply Closet', 'B3'],
    ['1" Breakaways Bails', 6, 'Supply Closet', 'B3'],
    ['1 1/2" Breakaway Bails', 6, 'Supply Closet', 'B3'],
    ['Water Thiefs', 6, 'Supply Closet', 'B4'],
    ['Ground Y Supply', 3, 'Supply Closet', 'B4'],
    ['Ground Supply', 3, 'Supply Closet', 'B4'],
    ['Blitzfire', 1, 'Supply Closet', 'C1'],
    ['Strainers', 3, 'Supply Closet', 'C1'],
    ['Hose Edge Protectors', 3, 'Supply Closet', 'C1'],
    ['1 1/4" Nozzle Tips', 3, 'Supply Closet', 'C2'],
    ['1" Nozzle Tip', 3, 'Supply Closet', 'C2'],
    ['1 3/8" Nozzle Tips', 2, 'Supply Closet', 'C2'],
    ['1 1/2" Nozzle Tip', 1, 'Supply Closet', 'C2'],
    ['1 3/4" Nozzle Tip', 1, 'Supply Closet', 'C2'],
    ['2" Nozzle Tip', 1, 'Supply Closet', 'C2'],
    ['1 1/8" Nozzle Tip', 1, 'Supply Closet', 'C2'],
    ['2 1/2" Elbows', 7, 'Supply Closet', 'C2'],
    ['1 1/2" Double Males', 9, 'Supply Closet', 'C2'],
    ['1 1/2" Couplings', 7, 'Supply Closet', 'C2'],
    ['2 1/2 Cap Pressure Gauge', 3, 'Supply Closet', 'C2'],
    ['Inline Pressure Gauge', 1, 'Supply Closet', 'C2'],
    ['2 1/2" to 1/2" Reducer', 1, 'Supply Closet', 'C2'],
    ['2 1/2" Female Caps', 5, 'Supply Closet', 'C2'],
    ['2 1/2" Male Caps', 3, 'Supply Closet', 'C2'],
    ['1 1/2" Female Caps', 3, 'Supply Closet', 'C2'],
    ['2 1/2 to 1" Reducers', 12, 'Supply Closet', 'C2'],
    ['Gated Wye', 4, 'Supply Closet', 'C3'],
    ['Gate Valves', 2, 'Supply Closet', 'C3'],
    ['Double Male 2 1/2"', 21, 'Supply Closet', 'C3'],
    ['Double Female 2 1/2"', 15, 'Supply Closet', 'C3'],
    ['2 1/2" Couplings', 2, 'Supply Closet', 'C3'],
    ['Siamese 2.5" with clapper valves', 3, 'Supply Closet', 'C4'],
    ['Siamese with 5" storz connection', 2, 'Supply Closet', 'C4'],
    ['Trimese 2.5"', 1, 'Supply Closet', 'C4'],
    ['Wye 2.5"', 2, 'Supply Closet', 'C4'],
    ['Hose Jacket', 1, 'Supply Closet', 'C4'],
    ['Foam Pick up tubes', 2, 'Supply Closet', 'C4'],
    ['Turbo draft (small)', 1, 'Supply Closet', 'C4'],
    ['Drafting appliances', 2, 'Supply Closet', 'C4'],
    ['Training Foam', 5, 'Supply Closet', 'D4'],
    ['Auto Wash', 1, 'Supply Closet', 'D4'],
    ['Fog Fluid', 2, 'Supply Closet', 'D4'],
    ['TK Charger', 5, 'Supply Closet', 'D4'],
    ['Vector Fog Machine', 3, 'Supply Closet', 'D4'],
    ['Marq Fog Machine', 2, 'Supply Closet', 'D4'],
    ['4" PVC Pipe', 4, 'Supply Closet', 'D3'],
    ['8" PVC Pipe', 1, 'Supply Closet', 'D3'],
    ['Sprinkler Wedge', 7, 'Supply Closet', 'D3'],
    ['Pipe Clamp', 4, 'Supply Closet', 'D3'],
    ['Male/Female Threaded PVC Caps 1" - 3/4"', 1, 'Supply Closet', 'D3'],
    ['Glue on PVC Caps', 5, 'Supply Closet', 'D3'],
    ['Cone Pipe Plug', 1, 'Supply Closet', 'D3'],
    ['Well Test', 1, 'Supply Closet', 'D3'],
    ['Crowbar', 5, 'Supply Closet', 'D3'],
    ['Ball-peen Hammer', 1, 'Supply Closet', 'D3'],
    ['Hammer', 1, 'Supply Closet', 'D3'],
    ['511 Tool', 1, 'Supply Closet', 'D3'],
    ['Spanner Wrench', 1, 'Supply Closet', 'D3'],
    ['Assortment of Allen Wrenches', 1, 'Supply Closet', 'D3'],
    ['Decon System', 25, 'Supply Closet', 'E1'],
    ['Blankets', 4, 'Supply Closet', 'E1'],
    ['Duffle Bag', 5, 'Supply Closet', 'E1'],
    ['Struts with Attachments', 8, 'Supply Closet', 'E2'],
    ['AAA Batteries', 24, 'Supply Closet', 'E3'],
    ['AA Batteries', 28, 'Supply Closet', 'E3'],
    ['D Battery', 1, 'Supply Closet', 'E3'],
    ['Allen Wrench Set Metric', 1, 'Supply Closet', 'E3'],
    ['Allen Wrench Set SAE', 1, 'Supply Closet', 'E3'],
    ['Allen Wrench Set Metric/SAE', 1, 'Supply Closet', 'E3'],
    ['Box Cutter', 1, 'Supply Closet', 'E3'],
    ['Frangible Bulb Sprinkler Head', 1, 'Supply Closet', 'E3'],
    ['Flat-headed Screwdriver', 2, 'Supply Closet', 'E3'],
    ['Philips Screwdriver', 1, 'Supply Closet', 'E3'],
    ['Mini Philips Screwdriver', 1, 'Supply Closet', 'E3'],
    ['Torx Screwdriver', 1, 'Supply Closet', 'E3'],
    ['Lockout', 8, 'Supply Closet', 'E3'],
    ['Open-ended Wrench', 1, 'Supply Closet', 'E3'],
    ['Slip-Joint Pliers', 1, 'Supply Closet', 'E3'],
    ['Dyke Cutters', 2, 'Supply Closet', 'E3'],
    ['Mini Hacksaw', 1, 'Supply Closet', 'E3'],
    ['Vice Grips', 3, 'Supply Closet', 'E3'],
    ['Adjustable Wrench', 1, 'Supply Closet', 'E3'],
    ['Wire Cutter', 1, 'Supply Closet', 'E3'],
    ['Pipe-Wrench', 1, 'Supply Closet', 'E3'],
    ['Air Cutting Chisel', 1, 'Supply Closet', 'E3'],
    ['20in Chainsaw Blade', 4, 'Supply Closet', 'E3'],
    ['Chainsaw Chain', 1, 'Supply Closet', 'E3'],
    ['9in Sawzaw Blade', 1, 'Supply Closet', 'E3'],
    ['Dremel', 1, 'Supply Closet', 'E3'],
    ['12in Hacksaw Blade', 15, 'Supply Closet', 'E3'],
    ['Carbide Sawzaw Blade', 12, 'Supply Closet', 'E3'],
    ['Air Lube', 2, 'Supply Closet', 'E3'],
    ['4-6in Spanner Wrench', 8, 'Supply Closet', 'E3'],
    ['5in Spanner Wrench', 13, 'Supply Closet', 'E3'],
    ['Smoke Trainer', 1, 'Supply Closet', 'E3'],
    ['Come-along', 2, 'Supply Closet', 'E3'],
    ['Come-along Bar', 6, 'Supply Closet', 'E3'],
    ['Rope Edge Protection', 2, 'Supply Closet', 'E3'],
    ['Dewalt Carrying Bag', 1, 'Supply Closet', 'E4'],
    ['Hydraram', 1, 'Supply Closet', 'E4'],
    ['Rescue Tech Bag', 1, 'Supply Closet', 'E4'],
    ['Chainsaw Safety Chap', 1, 'Supply Closet', 'F1'],
    ['Yates', 1, 'Supply Closet', 'F1'],
    ['Frisbees', 1, 'Supply Closet', 'F1'],
    ['12x15 4-mil Clear Bags', 2, 'Supply Closet', 'F1'],
    ['Big Easy Carrying Bag', 1, 'Supply Closet', 'F1'],
    ['Pop-up Traffic Cone with Carrying Bag', 4, 'Supply Closet', 'F1'],
    ['Universal Lockout Tool Set', 4, 'Supply Closet', 'F2'],
    ['Air Wedge', 6, 'Supply Closet', 'F2'],
    ['Glassmaster', 1, 'Supply Closet', 'F2'],
    ['K-Tool', 3, 'Supply Closet', 'F2'],
    ['Search and Rescue Gloves', 1, 'Supply Closet', 'F2'],
    ['Flag Pole Mount', 1, 'Supply Closet', 'F2'],
    ['Conversion Kit', 2, 'Supply Closet', 'F2'],
    ['Spring Rope Hook', 1, 'Supply Closet', 'F2'],
    ['Wedge Pack', 1, 'Supply Closet', 'F2'],
    ['Cooler Cable', 5, 'Supply Closet', 'F2'],
    ['Access Tool', 1, 'Supply Closet', 'F2'],
    ['Access Tool Kit', 1, 'Supply Closet', 'F2'],
    ['Cutters Edge Tool Sling', 5, 'Supply Closet', 'F2'],
    ['Hot Stick', 1, 'Supply Closet', 'F2'],
    ['AC Voltage Detector', 1, 'Supply Closet', 'F2'],
    ['Red Case with Steel Rods', 2, 'Supply Closet', 'F2'],
    ['Access Tool Bag', 1, 'Supply Closet', 'F2'],
    ['Pick Headed Axe', 6, 'Supply Closet', 'F3'],
    ['Flat Headed Axe', 5, 'Supply Closet', 'F3'],
    ['Sledge Hammer', 6, 'Supply Closet', 'F3'],
    ['Mini Sledge', 1, 'Supply Closet', 'F3'],
    ['Rubber Mallet', 1, 'Supply Closet', 'F3'],
    ['Style-50 Bar', 11, 'Supply Closet', 'F3'],
    ['Mini Shovel', 1, 'Supply Closet', 'F3'],
    ['Mini Halligan', 1, 'Supply Closet', 'F3'],
    ['Storm Drain Tool', 1, 'Supply Closet', 'F3'],
    ['Hacksaw', 1, 'Supply Closet', 'F3'],
    ['Quick Strap Mounting System', 1, 'Supply Closet', 'F3'],
    ['Box of Forcible Entry Tool Straps', 1, 'Supply Closet', 'F3'],
    ['36in Bolt Cutters', 3, 'Supply Closet', 'F3'],
    ['2 Sided Spannered Hydrant Wrench', 4, 'Supply Closet', 'F4'],
    ['1 Sided Spannered Hydrant Wrench', 3, 'Supply Closet', 'F4'],
    ['Hydrant Wrench', 1, 'Supply Closet', 'F4'],
    ['FLIR TIC Case', 1, 'Supply Closet', 'F4'],
    ['Carpenter Square', 3, 'Supply Closet', 'F4'],
    ['Keiser Deadblow 10lb', 1, 'Supply Closet', 'F4'],
    ['Sprinkler Assortment in Ammo Can', 1, 'Supply Closet', 'F4'],
    ['Water Can', 5, 'Supply Closet', 'F4'],
    ['CO2 Can', 1, 'Supply Closet', 'F4'],
];

foreach ($equipmentData as $item) {
    [$name, $qty, $location, $shelf] = $item;
    
    $equipment = \App\Models\EquipmentItem::create([
        'name' => $name,
        'normalized_name' => strtolower($name),
        'category' => 'Fire Equipment',
        'description' => "Location: $location, Shelf: $shelf",
        'unit_of_measure' => 'each',
        'reorder_min' => max(1, intval($qty * 0.2)),
        'reorder_max' => intval($qty * 2),
        'is_active' => true,
    ]);
    
    // Create initial stock mutation
    \DB::table('stock_mutations')->insert([
        'stockable_type' => $stockableType,
        'stockable_id' => $equipment->id,
        'stocker_type' => 'App\\Models\\User',
        'stocker_id' => 1,
        'amount' => $qty,
        'description' => 'Initial inventory count',
        'reference' => 'IMPORT-' . date('Ymd'),
        'created_at' => now(),
        'updated_at' => now(),
    ]);
}
echo "Imported " . count($equipmentData) . " equipment items\n";

// Import apparatus data from latest report (11/21/25)
$apparatusData = [
    ['002-16', 'E 21', 'Reserve', 'Fire Fleet', 'Available', 'ENGINE'],
    ['002-14', 'E 11', 'Reserve', 'Station 1', 'Available', 'ENGINE'],
    ['002-10', 'E 31', 'Reserve', 'Station 2', 'Available', 'ENGINE'],
    ['1033', '', 'Reserve', 'Station 1', 'Available', 'RESCUE'],
    ['1034', '', 'Reserve', 'Station 2', 'Available', 'RESCUE'],
    ['1035', '', 'Reserve', 'Station 1', 'In Service', 'RESCUE'],
    ['1036', '', 'Reserve', 'Station 2', 'Available', 'RESCUE'],
    ['14500', '', 'Reserve', 'Station 2', 'Available', 'RESCUE'],
    ['002-6', 'L 11', 'Reserve', 'Station 3', 'In Service', 'LADDER'],
    ['14501', '', 'Reserve', 'Station 3', 'Available', 'RESCUE'],
    ['20503', 'E 1', 'Station 1', 'Station 1', 'In Service', 'ENGINE'],
    ['002-12', 'L 1', 'Station 1', 'Fire Fleet', 'Out of Service', 'LADDER'],
    ['16508', 'R 1', 'Station 1', 'Fire Fleet', 'Out of Service', 'RESCUE'],
    ['19502', 'R 11', 'Station 1', 'Station 1', 'In Service', 'RESCUE'],
    ['002-20', 'A 1', 'Station 2', 'Station 2', 'In Service', 'AIR TRUCK'],
    ['18500', 'A 2', 'Station 2', 'Station 2', 'In Service', 'AIR TRUCK'],
    ['24509', 'E 2', 'Station 2', 'Station 2', 'In Service', 'ENGINE'],
    ['16507', 'R 2', 'Station 2', 'Station 2', 'In Service', 'RESCUE'],
    ['19503', 'R 22', 'Station 2', 'Station 2', 'In Service', 'RESCUE'],
    ['002-22', 'E 3', 'Station 3', 'Station 3', 'In Service', 'ENGINE'],
    ['17505', 'L 3', 'Station 3', 'Station 3', 'In Service', 'LADDER'],
    ['17501', 'R 3', 'Station 3', 'Station 3', 'In Service', 'RESCUE'],
    ['17503', 'R 44', 'Station 4', 'Station 4', 'In Service', 'RESCUE'],
    ['20504', 'E 4', 'Station 4', 'Station 4', 'In Service', 'ENGINE'],
    ['17502', 'R 4', 'Station 4', 'Station 4', 'In Service', 'RESCUE'],
];

foreach ($apparatusData as $a) {
    [$vehicleNo, $designation, $assignment, $currentLocation, $status, $classDesc] = $a;
    
    // Map status to valid values: 'In Service', 'Out of Service', 'Maintenance'
    $statusMap = ['In Service' => 'In Service', 'Out of Service' => 'Out of Service', 'Available' => 'In Service'];
    $mappedStatus = $statusMap[$status] ?? 'In Service';
    
    // Use designation or vehicleNo as unit_id
    $unitId = $designation ?: $vehicleNo;
    
    \App\Models\Apparatus::create([
        'unit_id' => $unitId,
        'make' => $classDesc,
        'model' => $assignment,
        'status' => $mappedStatus,
        'notes' => "Vehicle#: $vehicleNo, Location: $currentLocation, Assignment: $assignment",
    ]);
}
echo "Imported " . count($apparatusData) . " apparatus records\n";

echo "\nImport complete!\n";
