[program:reverb]
command=php /var/www/html/artisan reverb:start --host=0.0.0.0 --port=8080 --no-interaction
user=sail
environment=LARAVEL_SAIL="1"
stdout_logfile=/var/log/supervisor/reverb.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/var/log/supervisor/reverb_error.log
stderr_logfile_maxbytes=10MB
autostart=true
autorestart=true
