project:
  type: default
  output-dir: .

format:
  typst:
    toc: true
    toc-depth: 3
    number-sections: true
    section-numbering: "1.1.1"
    columns: 1
    margin:
      top: "1in"
      bottom: "1in"
      left: "1in"
      right: "1in"
    papersize: "us-letter"
    fontsize: "11pt"
