<?php

namespace App\Filament\Resources\ApparatusResource\RelationManagers;

use App\Filament\Resources\EquipmentItemResource;
use App\Filament\Resources\RecommendationResource;
use App\Models\AdminAlertEvent;
use App\Models\ApparatusDefectRecommendation;
use App\Models\ApparatusInventoryAllocation;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

class EquipmentRecommendationsRelationManager extends RelationManager
{
    protected static string $relationship = 'equipmentRecommendations';

    public function form(Form $form): Form
    {
        return $form
            ->schema([
                // Read-only form - recommendations created by system
                Forms\Components\Placeholder::make('info')
                    ->content('Equipment recommendations are automatically generated by the system based on defects.'),
            ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->recordTitleAttribute('equipment_item.name')
            ->modifyQueryUsing(fn (Builder $query) => 
                $query->whereHas('defect', fn ($q) => 
                    $q->where('apparatus_id', $this->ownerRecord->id)
                )
            )
            ->columns([
                Tables\Columns\TextColumn::make('defect.compartment')
                    ->label('Compartment')
                    ->searchable()
                    ->sortable(),
                
                Tables\Columns\TextColumn::make('defect.item')
                    ->label('Defect Item')
                    ->searchable(),
                
                Tables\Columns\TextColumn::make('equipment_item.name')
                    ->label('Recommended Item')
                    ->searchable()
                    ->url(fn ($record) => 
                        $record->equipment_item ? 
                        EquipmentItemResource::getUrl('edit', ['record' => $record->equipment_item_id]) : 
                        null
                    ),
                
                Tables\Columns\TextColumn::make('match_confidence')
                    ->label('Confidence')
                    ->formatStateUsing(fn ($state) => number_format($state * 100, 0) . '%')
                    ->badge()
                    ->color(fn ($state) => 
                        $state >= 0.8 ? 'success' : 
                        ($state >= 0.5 ? 'warning' : 'danger')
                    ),
                
                Tables\Columns\TextColumn::make('recommended_qty')
                    ->label('Qty'),
                
                Tables\Columns\BadgeColumn::make('status')
                    ->colors([
                        'warning' => 'pending',
                        'success' => 'allocated',
                        'danger' => 'dismissed',
                    ]),
                
                Tables\Columns\TextColumn::make('created_at')
                    ->label('Recommended')
                    ->since()
                    ->sortable(),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('status')
                    ->options([
                        'pending' => 'Pending',
                        'allocated' => 'Allocated',
                        'dismissed' => 'Dismissed',
                    ]),
            ])
            ->headerActions([
                // No header actions - recommendations created automatically
            ])
            ->actions([
                Tables\Actions\Action::make('allocate')
                    ->label('Allocate')
                    ->icon('heroicon-o-check-circle')
                    ->color('success')
                    ->visible(fn ($record) => $record->status === 'pending' && $record->equipment_item_id)
                    ->form([
                        Forms\Components\TextInput::make('qty_to_allocate')
                            ->label('Quantity to Allocate')
                            ->numeric()
                            ->required()
                            ->default(fn ($record) => $record->recommended_qty)
                            ->minValue(1),
                        
                        Forms\Components\Textarea::make('notes')
                            ->label('Allocation Notes')
                            ->rows(3),
                    ])
                    ->action(function (ApparatusDefectRecommendation $record, array $data) {
                        $equipmentItem = $record->equipmentItem;
                        
                        // Check stock availability
                        if ($equipmentItem->stock < $data['qty_to_allocate']) {
                            Notification::make()
                                ->danger()
                                ->title('Insufficient Stock')
                                ->body("Only {$equipmentItem->stock} units available")
                                ->send();
                            return;
                        }
                        
                        // Create allocation
                        $allocation = ApparatusInventoryAllocation::create([
                            'apparatus_id' => $record->defect->apparatus_id,
                            'equipment_item_id' => $record->equipment_item_id,
                            'apparatus_defect_id' => $record->apparatus_defect_id,
                            'qty_allocated' => $data['qty_to_allocate'],
                            'allocated_by_user_id' => auth()->id(),
                            'allocated_at' => now(),
                            'notes' => $data['notes'] ?? null,
                        ]);
                        
                        // Deduct stock
                        $equipmentItem->decrement('stock', $data['qty_to_allocate']);
                        
                        // Update recommendation status
                        $record->update([
                            'status' => 'allocated',
                            'allocated_at' => now(),
                            'allocated_by_user_id' => auth()->id(),
                        ]);
                        
                        // Create alert event
                        AdminAlertEvent::create([
                            'type' => 'inventory_allocated',
                            'severity' => 'info',
                            'message' => "{$data['qty_to_allocate']} x {$equipmentItem->name} allocated to {$record->defect->apparatus->unit_id}",
                            'related_type' => 'apparatus_inventory_allocation',
                            'related_id' => $allocation->id,
                            'created_by_user_id' => auth()->id(),
                        ]);
                        
                        Notification::make()
                            ->success()
                            ->title('Equipment Allocated')
                            ->body("{$data['qty_to_allocate']} units allocated successfully")
                            ->send();
                    }),
                
                Tables\Actions\Action::make('view_details')
                    ->label('View Details')
                    ->icon('heroicon-o-arrow-right')
                    ->url(fn ($record) => RecommendationResource::getUrl('edit', ['record' => $record])),
            ])
            ->bulkActions([
                // No bulk actions
            ])
            ->defaultSort('created_at', 'desc')
            ->emptyStateHeading('No equipment recommendations yet')
            ->emptyStateDescription('Recommendations will appear here when defects are detected.')
            ->emptyStateIcon('heroicon-o-light-bulb');
    }
}
