<?php

declare(strict_types=1);

return [
    'models' => [
        App\Models\User::class => 'admin.members',
        App\Models\Apparatus::class => 'admin.fleet',
        App\Models\ApparatusDefect::class => 'admin.fleet',
        App\Models\ApparatusDefectRecommendation::class => 'admin.fleet',
        App\Models\ApparatusInspection::class => 'admin.fleet',
        App\Models\ApparatusServiceTicket::class => 'admin.fleet',
        App\Models\ShopWork::class => 'admin.fleet',
        App\Models\UnitMasterVehicle::class => 'admin.fleet',
        App\Models\Station::class => 'admin.stations',
        App\Models\StationInspection::class => 'admin.stations',
        App\Models\StationRequest::class => 'admin.stations',
        App\Models\RoomAsset::class => 'admin.stations',
        App\Models\SingleGasMeter::class => 'admin.stations',
        App\Models\AssignedEquipment::class => 'admin.equipment',
        App\Models\EmployeeEquipmentRequest::class => 'admin.equipment',
        App\Models\EquipmentItem::class => 'admin.equipment',
        App\Models\FireEquipmentRequest::class => 'admin.equipment',
        App\Models\InventoryItem::class => 'admin.equipment',
        App\Models\InventoryLocation::class => 'admin.equipment',
        App\Models\PersonnelRequest::class => 'admin.personnel',
        App\Models\Employee::class => 'admin.personnel',
        App\Models\Training\TrainingTodo::class => 'admin.training',
        App\Models\Workgroup::class => 'admin.workgroups',
        App\Models\WorkgroupMember::class => 'admin.workgroups',
        App\Models\WorkgroupFile::class => 'admin.workgroups',
        App\Models\WorkgroupSession::class => 'admin.workgroups',
        App\Models\CandidateProduct::class => 'admin.workgroups',
        App\Models\EvaluationCategory::class => 'admin.workgroups',
        App\Models\EvaluationCriterion::class => 'admin.workgroups',
        App\Models\EvaluationSubmission::class => 'admin.workgroups',
        App\Models\EvaluationTemplate::class => 'admin.workgroups',
        App\Models\OperationalFormRecord::class => 'admin.forms',
        App\Models\CapitalProject::class => 'admin.projects',
        App\Models\Under25kProject::class => 'admin.projects',
        App\Models\Todo::class => 'admin.notifications',
        App\Models\InboundEmail::class => 'admin.communications',
        App\Models\OutboundEmail::class => 'admin.communications',
    ],
];
