<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        @page {
            margin: 0.75in;
        }
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 11px;
            line-height: 1.5;
            color: #292524;
        }
        .header {
            text-align: center;
            border-bottom: 3px solid #B91C1C;
            padding-bottom: 12px;
            margin-bottom: 24px;
        }
        .header h1 {
            font-size: 20px;
            color: #B91C1C;
            margin: 0 0 4px 0;
        }
        .header .subtitle {
            font-size: 13px;
            color: #57534E;
            margin: 0;
        }
        .header .meta {
            font-size: 10px;
            color: #A8A29E;
            margin-top: 6px;
        }
        h2 {
            font-size: 15px;
            color: #1C1917;
            border-bottom: 1px solid #D6D3D1;
            padding-bottom: 4px;
            margin-top: 20px;
        }
        h3 {
            font-size: 13px;
            color: #44403C;
            margin-top: 14px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 10px 0;
            font-size: 10px;
        }
        thead th {
            background-color: #292524;
            color: #FAFAF9;
            padding: 6px 8px;
            text-align: left;
            font-weight: 600;
        }
        tbody td {
            padding: 5px 8px;
            border-bottom: 1px solid #E7E5E4;
        }
        tbody tr:nth-child(even) {
            background-color: #FAFAF9;
        }
        strong {
            color: #1C1917;
        }
        ul, ol {
            padding-left: 20px;
        }
        li {
            margin-bottom: 3px;
        }
        .footer {
            text-align: center;
            font-size: 9px;
            color: #A8A29E;
            border-top: 1px solid #E7E5E4;
            padding-top: 8px;
            margin-top: 30px;
        }
        p {
            margin: 6px 0;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p class="subtitle">{{ $workgroupName }} — Miami Beach Fire Department</p>
        <p class="meta">Generated: {{ $generatedAt }}</p>
    </div>

    <div class="content">
        {!! $reportHtml !!}
    </div>

    <div class="footer">
        <p>{{ $workgroupName }} — Miami Beach Fire Department Health &amp; Safety Committee</p>
        <p>This document was generated by the MBFD Hub AI Analytics System on {{ $generatedAt }}</p>
    </div>
</body>
</html>
