name: Lighthouse CI

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@3e7e23fb74242897f95c0ba9cabad3d0227b9b18 # v12
        with:
          urls: |
            https://www.mbfdhub.com/
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
